# Generated by Django 4.1.3 on 2022-12-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiProject', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderstatus',
            name='id',
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='order_number',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
