# Generated by Django 4.1.3 on 2022-12-04 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=70)),
                ('order_date', models.DateField()),
                ('qt_ordd', models.IntegerField()),
            ],
        ),
    ]
